plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-minimal
title: Guidelines
description: Workflow guidelines to be followed
